using AiPlugin.Domain.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AiPlugin.Domain.User
{
    /// <summary>
    /// User entity.
    /// Each user has an Id (firebaseId), email and datetime of creation.
    /// And every user has a flag that shows if it has accepted the privacy policy
    /// </summary>
    public class User : IDeleted
    {
        /// <summary>
        /// User Id generated by Firebase
        /// </summary>
        [Key]
        public string Id { get; set; } = null!;
        public string Email { get; set; } = null!;
        /// <summary>
        /// Flag that gives shows that the user accepted the privacy policy
        /// </summary>
        public bool isPrivacyAccepted { get; set; }
        public DateTime CreatedAt { get; set; }
        public bool isDeleted { get; set; }
    }
}
